ROW_SIZE_WORDS = 32
ROW_SIZE_BYTES = 2*ROW_SIZE_WORDS
PRG_ROM_SIZE_WORDS = 0x2000
PRG_ROM_SIZE_BYTES = 2*PRG_ROM_SIZE_WORDS
CONFIG_ADDR_WORDS = 0x8000
CONFIG_ADDR_BYTES = 2*CONFIG_ADDR_WORDS
PRG_ROM_ROW_COUNT = PRG_ROM_SIZE_WORDS // ROW_SIZE_WORDS

PACKED_DATA_START_ADDR_WORDS = 0x1400
